baseURL = "https://mattriley.info/blog/"
languageCode = "en-gb"
title = "Matt Riley Info - Blog"
publishDir = "../home/public/blog"
theme = "info"

[Author]
  name = "Matt"

[params]
  Subtitle = "Your site's subtitle/tagline"
  GithubID = "matt-riley"
  TwitterID = "mjr1878"
  Summary = true # takes true or false
  Content = false # takes true or false
  mainSections = ["post"]