on:
  push:
    branches:
      - master
    paths:
      - cloud-functions/**  
name: Deploy Cloud Functions to Firebase
jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ hashFiles('**/yarn.lock') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: yarn install --ignore-engines
      - name: Deploy
        run: npm install -g firebase-tools && firebase deploy --only functions:artistTotals,functions:getArtist,functions:getLabel,functions:releaseTotals,functions:getArtistImgs,functions:getReleaseImgs,functions:getLabelImgs,functions:updateImgs
        working-directory: ./cloud-functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
