on:
  push:
    branches:
      - master
    paths:
      - cloud-functions/**  
name: Deploy Cloud Functions to Firebase
jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-node${{ hashFiles('**/yarn.lock') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: npm i
        working-directory: ./cloud-functions/functions
      - name: To firebase and beyond!
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./cloud-functions
