on:
  push:
    branches:
      - master
    paths:
      - home/**
      - blog/**
name: Deploy Home to Firebase
env:
  NODE_ENV: production
jobs:
  deploy:
    name: Deploy Home
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: yarn install --ignore-engines --production=false
      - name: Build Home
        run: yarn workspace home run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
