on: pull_request
name: Check builds
jobs:
  runBuild:
    name: Run builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node_version: 10
      - name: Install Deps if no cache
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Execute build
        run: yarn workspaces run build
  automerge:
    runs-on: ubuntu-latest
    needs: runBuild
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.9.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
          MERGE_LABELS: "dependencies"
